name: C/C++ CI

on:
  push:
    branches: [ "GithubActions" ]
  pull_request:
    branches: [ "GithubActions" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libgl1-mesa-dev xorg-dev
        
    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build

    - name: Run tests
      run: build/test/testByMinifb
